### PR TITLE
NAF additions

### PR DESCRIPTION
**Pull request by zupon**
This PR adds new clusters from the ontology tool in the proper place in the ontology (concept, process, property, not just "clusters"). Polarity and semantic type have been adjusted accordingly.

### CODE REVIEW

**Comment by kwalcock** [comment]
I'm not sure whether any of these differences are important:

Current | Suggested
--- | ---
harrassment | harassment
sepratist | separatist
aspirine | aspirin
expell | expel
persistant | persistent
camraderie | camaraderie

**Review by BeckySharp — APPROVED** [review]
thanks @zupon !

**Comment by jmacbrid** [comment]
OK to go ahead and merge this?  I want to make sure I have the final version before starting the clustering run.

**Review by bgyori — APPROVED** [review]

**Comment by BeckySharp** [comment]
@jmacbrid if you run into any problems with it please let us know, thanks!

**Pull request merged**
