### PR TITLE
Ontology extension exercise

### PR DESCRIPTION
**Pull request by zupon**
Adds new nodes from today's ontology extension exercise.  All new nodes are currently placed under `wm/concept/clusters/`. There are a few that _might_ potentially be better under `process`, including:
- peacebuilding_efforts
- natural_disaster
- humanitarian_assistance
- herding
- exploration
- ethnic_conflict
- environmental_degredation
- election_process
- crackdown

There were two different occurrences of `environmental_degredation` as new nodes. One of them only had `environmental_impacts` as an example, so I just renamed that node to `environmental_impacts`. I could also just move that example into the other node.

By default, the `semantic type` field in the UI was set to `event`. I changed the field to `event` for the new nodes (only), but these need to be checked @spilioeve

### CODE REVIEW

**Review by bgyori — APPROVED** [review]
Looks good to me!

**Review by BeckySharp — APPROVED** [review]
awesome thanks!!

**Comment by BeckySharp** [comment]
@spilioeve hopefully you can review too to make sure this doesn’t break anything for you

**Comment by spilioeve** [comment]
Okay I reviewed it and changed the semantic type in the new fields. Please
lmk if you can view the changes

**Comment by kwalcock** [comment]
I see the changes, but can they be turned into a PR against this branch?

**Comment by kwalcock** [comment]
Nevermind.  You are a step ahead of me.

**Pull request merged**
