### PR TITLE
revisions to the ontology based on Ontology telecon

### PR DESCRIPTION
**Pull request by chanys**
I followed Pascale's pdf/slides almost to the letter, making very slight adjustments as it makes sense. 

The following are things which I am unsure about:

Can we put examplar keywords under non-leaf nodes? I do not know how, so
Instead of Pascale's suggested:
```
-revenue:
 - household_income:
   - farmer_income
```

I put:
```
- revenue:
  - household_income
  - farmer_income
```

, which allows me to insert keywords into household_income

* And because of the above inability to insert keywords into non-leaf nodes, I have commented out some prior keywords with '#'. E.g. search for "#- livelihood". Those keywords there belong to the previous leaf node 'livelihood', which is now an intermediate node with children (foraging, hunting, and farming)

* Another are commented out keywords under 'revenue'

Slide 13:
* Slide 13 suggests that 'condition' branch could be removed. I did not do that; see if you agree with the current 'condition' branch.
* Slide 13 also suggests adding 'resilence' under food_security. I did not do that. Did you catch what is meant by food_resilence? 

#####
I introduced a new concept 'malnutrition' (because we had some malnutrition keywords) , and tagged it as opposite of food_diversity

### CODE REVIEW

**Comment by BeckySharp** [comment]
THANKS @chanys ! 
I will review this in detail tomorrow and see if I can help!

**Comment by chanys** [comment]
@BeckySharp , could you also please get whoever wrote the auto-check-scripts (Keith?) to see what are the failures? The script doesn't exactly say what tests fail, which makes it hard to debug. Thanks.

**Comment by BeckySharp** [comment]
sure, @kwalcock is the one, and I can look tomorrow if he hasn't beaten me to it :)

**Comment by kwalcock** [comment]
Keith is looking.

**Comment by kwalcock** [comment]
It didn't like the empty examples.  I'm fixing another small thing or two.

**Comment by kwalcock** [comment]
It's happy now.

**Comment by chanys** [comment]
Thanks!

**Comment by chanys** [comment]
I probably missed the discussions on the food_shortage and water_shortage (are there anymore?). 

As parallels to (food_availability, food_access, food_utilization, food_stability), I introduced (food_unavailability, food_nonaccess, food_nonutilization, food_instability) where I sort of divided up the keywords from food_shortage. I could collapse all these back into food_shortage. What do you think?

Is water_shortage any different from water_insecurity? They overlap in keywords.

Sure, we can remove the opposite links between food_diversity and malnutrition.

**Comment by BeckySharp** [comment]
oh, sorry, I think I missed that! :(

let me look again!

**Comment by chanys** [comment]
I have removed the opposite links between food_diversity and malnutrition.

**Comment by BeckySharp** [comment]
entonces, should we merge?

**Comment by chanys** [comment]
If you think what I did is OK, please do merge.

**Comment by BeckySharp** [comment]
I think that I will no go through the examples and add maybe add stuff, but this is great!

**Pull request merged**
