### PR TITLE
Processes from clusters

### PR DESCRIPTION
**Pull request by zupon**
Adds 20 new processes and new examples to 6 existing processes based on clusters inspired by BBN.

### CODE REVIEW

**Review by BeckySharp — APPROVED** [review]
Thanks!

**Comment by zupon** [comment]
@BeckySharp is this safe to merge?

**Comment by BeckySharp** [comment]
I'm going to -- @bgyori @kwalcock Head's up!

**Comment by kwalcock** [comment]
Thanks, all.

**Pull request merged**
