### PR TITLE
Start Python testing

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Here's *one* way to arrange for testing of the Python scripts.  I didn't move them to e.g. src/main/python and src/test/python because it seems like people will want to run the scripts and do it from somewhere near the top, independent of sbt things.  Tests are one level down.  If that is not handy, someone will surely let me know.  .travis.yml is altered slightly to run the tests in a python environment (rather than from sbt as we're doing on Jenkins).  It would be fine (with me) to swap out Travis for Github tests.  As soon as there is a real test, the factorial files can also be done away with.  Local sbt developers can run `sbt testPython` for a sanity check, assuming pytest is installed.  HTH.

**Review by MihaiSurdeanu — APPROVED** [review]
Nice. Thanks @kwalcock !

**Comment by zupon** [comment]
Looks good! Is this okay to merge and start trying to write tests for the other scripts?

**Comment by kwalcock** [comment]
@zupon, would be you able to merge this branch into what you are working on before this gets to master?  There is a parallel development in a different branch and there may need to be a reconciliation before master.  It would be useful to find out how well this version works with what you are trying to do, though.

**Comment by zupon** [comment]
@kwalcock I'll try that and let you know how it goes with my branch.

**Pull request merged**
