### PR TITLE
added v2.1 compositional ontology

### PR DESCRIPTION
**Pull request by BeckySharp**
OK, a version of the compositional ontology, I did my best to add the old metadata in.
I found an issue with the script, but only _after_ I had already added a ton of metadata.  I will update the script at some point, but wanted to get this in for people to use.

Please look over!

### CODE REVIEW

**Comment by chanys** [comment]
+1

I did various spot checks and things seem fine. This is a much coarser review than what i usually do, due to time limitations and also because this is an entirely new ontology (so it's quite implausible to manually verify each and every node).

@MihaiSurdeanu please merge when you've done reviewing.

**Comment by chanys** [comment]
@BeckySharp @MihaiSurdeanu , can we merge this into master? I'm planning to start making use of the yaml this afternoon. Thanks.

**Comment by MihaiSurdeanu** [comment]
Ok with me.
Mihai


On August 25, 2020 at 9:20:49 AM, chanys (notifications@github.com) wrote:

@BeckySharp <https://github.com/BeckySharp> @MihaiSurdeanu
<https://github.com/MihaiSurdeanu> , can we merge this into master? I'm
planning to start making use of the yaml this afternoon. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WorldModelers/Ontologies/pull/71#issuecomment-680127908>,
or unsubscribe

**Comment by chanys** [comment]
We probably should let all readers know that this is in. Thanks!

**Comment by BeckySharp** [comment]
@chanys we're going to add some of the other nodes from #69 here, @zupon is doing this today.

**Comment by BeckySharp** [comment]
> We probably should let all readers know that this is in. Thanks!

I'd like to wait a teeny bit (few hours) until that change is in before we let others know

**Pull request merged**
