### PR TITLE
More edits

### LINKED ISSUE #74: spelling error
https://github.com/WorldModelers/Ontologies/blob/25690a258d02fdf1f35ce9140f7cd54145e2b30c/CompositionalOntology_v2.1_metadata.yml#L1365

should be "emigrate"

### PR DESCRIPTION
**Pull request by zupon**
Addresses issues raised about the compositional ontology AND breaks up compositional concepts into their respective branches.

Some remaining questions:
1. `food_preference` and `food_intake` nodes:  There's already a `food` CONCEPT, so I removed "food" from the names/examples of these nodes. Is that alright, or are these something more specific where we _do_ want to keep "food" involved?
2. `living_condition`: `condition` has been added as a PROPERTY, but after removing it from this node I'm not sure what's left. Is a `life` CONCEPT alright?
3. `economic_development` and `economic_crisis`:  Not sure how to separate out `development` and `crisis` here.
4. `physical_insecurity`:  There's an `insecurity` PROPERTY, but if we get rid of that here I'm not sure what we're left with. Maybe that same potential `life` CONCEPT?

Closes #74, #77, #78, #79, #81, #84, #86, #87, #88, #89, #90, #91

### CODE REVIEW

**Comment by BeckySharp** [comment]
> Some remaining questions:
> 
> 1. `food_preference` and `food_intake` nodes:  There's already a `food` CONCEPT, so I removed "food" from the names/examples of these nodes. Is that alright, or are these something more specific where we _do_ want to keep "food" involved?

nope, having just intake and preference should be fine, and I guess those should be processes (or preference a property)

> 2. `living_condition`: `condition` has been added as a PROPERTY, but after removing it from this node I'm not sure what's left. Is a `life` CONCEPT alright?

fine with me :)

> 3. `economic_development` and `economic_crisis`:  Not sure how to separate out `development` and `crisis` here.

I think we can separate `development` and `crisis` and leave something like `economy`

> 4. `physical_insecurity`:  There's an `insecurity` PROPERTY, but if we get rid of that here I'm not sure what we're left with. Maybe that same potential `life` CONCEPT?

maybe? seems reasonable, maybe others have a better idea?

**Review by BeckySharp — CHANGES_REQUESTED** [review]
I think we need to split out `worker` from `healthcare_worker`, worker can stay in entities (or something like `workforce` or `staff` in concept?) and then we can leave in `healthcare` as a concept?

what do you think?

**Comment by MihaiSurdeanu** [comment]
On 4. I think `life` is a decent approximation here!

**Comment by BeckySharp** [comment]
thanks @zupon !!

**Comment by zupon** [comment]
One more question about `economic_crisis`. If I split it into  `economy` and `crisis` CONCEPTs, will that be a problem since both of the relevant ones are CONCEPTs? If we only take the top 1, we'd lose the other one. What if we just rename that node `depression_recession` and keep everything else as is? Is that cheating?

**Comment by BeckySharp** [comment]
> One more question about `economic_crisis`. If I split it into `economy` and `crisis` CONCEPTs, will that be a problem since both of the relevant ones are CONCEPTs? If we only take the top 1, we'd lose the other one. What if we just rename that node `depression_recession` and keep everything else as is? Is that cheating?

no, not a problem, at least for UAZ, others can chime in if so

**Comment by lgalescu** [comment]
on "living conditions":

this phrase is idiomatic, so i wouldn't break it down, certainly not as a property of "life". it really means "welfare" (in the general sense, not the specific sense of "social assistance" used in the US). i think we should have a "welfare" concept, and "living conditions" as a phrase should map to that.

**Review by BeckySharp — APPROVED** [review]

**Comment by BeckySharp** [comment]
Thanks @zupon  and @lgalescu  for the edits and comments!
As soon as the tests pass I'll merge it and we can roll with this next version!

**Pull request merged**
