### PR TITLE
Zupon feb2020 interventions metadata

### PR DESCRIPTION
**Pull request by zupon**
Added examples for new interventions ontology branch and created new `wm_flat` ontology using it.

### CODE REVIEW

**Comment by kwalcock** [comment]
I did a test locally and get an error with these two:
Duplicate leaf: ArrayBuffer(wm, concept, causal_factor, interventions, build, shelter)
Duplicate leaf: ArrayBuffer(wm, concept, causal_factor, agriculture, planting)

At some point a rule was made against leaves with the same name.  Here are the duplicates:
ArrayBuffer(wm, concept, causal_factor, interventions, provide, livelihood_support, humanitarian_non_food_items, shelter)
ArrayBuffer(wm, concept, causal_factor, interventions, train, agriculture_training, production_practices, planting)

**Comment by kwalcock** [comment]
Eidos doesn't care about the duplicate leaf node names, so it is using the ontology anyway.

**Comment by BeckySharp** [comment]
cool thanks!

**Comment by kwalcock** [comment]
I will update the configuration to process the new file.

**Comment by BeckySharp** [comment]
I mean -- it processed the file, that wasn't the problem, I am unsure who
ranks and takes the topK of the nodes

**Comment by kwalcock** [comment]
Sorry, I mean to perform the unit tests on the new file and to export it for use.

**Comment by kwalcock** [comment]
Keith is confused.  The unit test error messages I mentioned above were for a wm_flat_metadata.yml file that was sent to me via email.  wm_flat is mentioned above, but it's not directly part of the repo.  So, the error messages are mostly irrelevant.  I did run the tests on the file feb2020_interventions.yaml afterwards, and this file is part of the repo.  That file does not pass, but then perhaps that was the idea.  It appears to have no leaf nodes contained.  It must be used for something different.

**Comment by zupon** [comment]
The `feb2020_interventions.yml` is the human-readable version, so it does not have most of the relevant information we need. `feb2020_interventions_metadata.yml` is where I started adding my examples for the new nodes, and that ultimately got added to `wm_flat_metadata.yml`, where Zhengzhong also added his examples. `wm_flat_metadata.yml` is just the previous flat ontology (`wm_with_flattened_interventions.yml`) with the `intervention` branch replaced by our new intervention branch.

**Comment by kwalcock** [comment]
Plus, I didn't look for the file in the right branch.  Thanks!  However, when I test it (wm_flat_metadata.ytml), the same two errors from before are noted.  At some point we didn't want to allow leaf nodes with the same names.  Perhaps that's no longer important.  Just so you know.

**Comment by BeckySharp** [comment]
FYI @bnmin @chanys @MihaiSurdeanu 
Added metadata -- for simplicity made copy of interventions in the previous wm ontology, but relacing the interventions branch, the files are:
`wm_flat.yml` and `wm_flat_metadata.yml` 

feel free to edit to your heart's content!!

**Pull request merged**
