### PR TITLE
rearranged ontology for compositional grounder

### PR DESCRIPTION
**Pull request by zupon**
I rearranged the wm ontology to work with the compositional grounder. There are some comments describing new nodes added, as well as some questions about what may still need to be changed. Includes both the version with metadata as well as the human-readable version.

### CODE REVIEW

**Comment by BeckySharp** [comment]
THANKS!!! I looked briefly and looks great, I'll dig in some myself and address some of your questions, but THANKS!!! I imagine you're a bit blocked until this is done?  Or you can use the current one you PRd here to debug the eidos grounding stuff?

**Comment by BeckySharp** [comment]
@zupon as soon as you add the patterns and verify that both metadata and other versions are valid yml, re-push and I'll merge, thanks!

**Comment by chanys** [comment]
@BeckySharp : is wm_compositional.yml completely derived from wm.yml? i.e. the two yml files contain exactly the same set of nodes. wm_compositional.yml is just a re-arrangement of nodes from wm.yml. What is the motivation behind creating wm_compositional.yml? I know in WM, the plan is to: when given an unstructured phrase from a user (e.g. "increase in oil price"), turn it into a structured representation, i.e. ID the action/process "increase", the property "price", and the artifact "oil".

**Comment by chanys** [comment]
@BeckySharp : is wm_compositional.yml completely derived from wm.yml? i.e. the two yml files contain exactly the same set of nodes. wm_compositional.yml is just a re-arrangement of nodes from wm.yml. What is the motivation behind creating wm_compositional.yml? I know in WM, the plan is to: when given an unstructured phrase from a user (e.g. "increase in oil price"), turn it into a structured representation, i.e. ID the action/process "increase", the property "price", and the artifact "oil".

**Comment by BeckySharp** [comment]
@chanys -- it is 100% derived/rearranged from the wm.yml -- but bc of the separation of events from phenomena, it's no longer a 1-1 map.  The plan here is *not* to replace the wm.yml, but to have a shared ontology that can be used to produce the lightly compositional groundings discussed at the last PI meeting (@MihaiSurdeanu feel free to chime in if I am misrepresenting)

**Comment by BeckySharp** [comment]
@chanyees @bnmin @MihaiSurdeanu I'm going to go ahead and merge this bc the files are separate and won't affect any of the current moving parts.  I imagine the compositional ontology will change, esp in light of the upcoming edits to the main one, but this gets the process out of a PR and into the real-world

**Pull request merged**
