### PR TITLE
Conf call edits

### PR DESCRIPTION
**Pull request by BeckySharp**
These are the edits discussed in the conference call today:

- removed the other branches (indicators, entities, etc) and thus removed the `causal_factor` level in the hierarchy.  This entailed deleting some and moving others elsewhere, feel free to request changes.
- i renamed a couple of places where the parent node and the child leaf had the same name, in a couple of places I deleted the child. I tried to be conscientious, but again, feel free to request changes and i'll do them
- I added a few `opposite: [path_to_opposite]` in places where I felt that it was reasonable to associate an increase in one with an inherent decrease in the other.  In a few places, I decided to *not* mark them bc I felt that the corresponding inc/dec wasn't really inherent (i.e., that a decrease in one meant more of a return to base, for example with "flooding" and "drought" -- reduced flooding doesn't entail increased drought, just less flooding.).  These are the changes I am most concerned about others disagreeing, so please check.  you can grep for "opposite" to easily find them.
- I removed the `take_args` metadata bc we're not going to use it, so trying to keep things cleaner...

FYI @bgyori

### CODE REVIEW

**Comment by bnmin** [comment]
Sorry for the delay. I wasn't in the telecon (Yee Seng was but he is not on Github). I'll ask him to review the PR and work on the remaining issue on Monday. Thanks!

**Comment by BeckySharp** [comment]
thanks! if more changes are needed just let me know!

**Comment by bnmin** [comment]
Yee Seng actually is on github:) His user id is chanys. Could you add Yee Seng into with an admin or developer access @BeckySharp @MihaiSurdeanu ? Thanks!

**Comment by bgyori** [comment]
We are starting to work on normalizing across opposite relationships based on this branch. I noticed that the `polarity` entries for both the inherently positive (e.g., food security) and negative (e.g., food insecurity) concepts are 1.0. Unless I misunderstand what polarity stands for, I think it would make sense to set polarity to -1 for negative concepts. That would allow us to normalize to one or the other more consistently (for instance always the positive concept) without having to hard code specific choices. Any thoughts?

**Comment by bgyori** [comment]
@BeckySharp I found an issue with the opposites: the paths seem to be missing the `causal_factor` level. e.g., 
```
opposite: wm/concept/access/food_shortage
```
should be
```
opposite: wm/concept/causal_factor/access/food_shortage
```
Could you please confirm that this is indeed the case?

**Comment by BeckySharp** [comment]
> We are starting to work on normalizing across opposite relationships based on this branch. I noticed that the `polarity` entries for both the inherently positive (e.g., food security) and negative (e.g., food insecurity) concepts are 1.0. Unless I misunderstand what polarity stands for, I think it would make sense to set polarity to -1 for negative concepts. That would allow us to normalize to one or the other more consistently (for instance always the positive concept) without having to hard code specific choices. Any thoughts?

Yes -- this is the plan, and it's been the plan for like, a year, but we haven't had the bandwidth yet.  It certainly won't be done by Monday... We also would ideally have something similar with the indicators, to handle the interplay

**Comment by BeckySharp** [comment]
I added the `causal_factor` back into the path of opposites, sorry for that bug

**Comment by BeckySharp** [comment]
> @BeckySharp I found an issue with the opposites: the paths seem to be missing the `causal_factor` level. e.g.,
> 
> ```
> opposite: wm/concept/access/food_shortage
> ```
> 
> should be
> 
> ```
> opposite: wm/concept/causal_factor/access/food_shortage
> ```
> 
> Could you please confirm that this is indeed the case?

@bgyori fixed, sorry!

**Comment by BeckySharp** [comment]
> Yee Seng actually is on github:) His user id is chanys. Could you add Yee Seng into with an admin or developer access @BeckySharp @MihaiSurdeanu ? Thanks!

done! fyi @chanys @bnmin

**Comment by bgyori** [comment]
I changed the polarities from float to int, and added negative polarities, for now, just for the 4 entries that have positive opposite pairs, hope this is okay.

**Comment by bgyori** [comment]
Uh oh, it looks like the opposites were added with `casual_factor` instead of `causal_factor`, I'm pushing a fix now.

**Comment by BeckySharp** [comment]
Haha, I'm awesome!

**Comment by BeckySharp** [comment]
> I changed the polarities from float to int, and added negative polarities, for now, just for the 4 entries that have positive opposite pairs, hope this is okay.

cool, thanks, and if you have thoughts about how we should move forward with others (i.e., how to fully use the polarities), please please let me know!
PS -- this reminds me, there was also once talk of adding other "modifiers" other than just INC/DEC/QUANT @bgyori , if you remember what some of them were can you please start an issue here or in Eidos?

**Pull request merged**
