### PR TITLE
Underscores

### PR DESCRIPTION
**Pull request by dianakolusheva**
This PR is to standardize the naming format across all entries in the ontology. It adds underscores to all node names (both leaf nodes and higher level category nodes). Examples are unchanged. Please let me know if that works for other teams.

### CODE REVIEW

**Comment by dianakolusheva** [comment]
> @dianakolusheva: I am generally Ok with this change. Is this needed for Indra?

@MihaiSurdeanu I believe there's no specific requirement for this in INDRA at this point. We found that some entries have underscores while others have spaces in current version ("food_security" vs "crop season"). @bgyori and I discussed this with @BeckySharp in recent email (should be on darpa-wm mailing list) and agreed it would be good to standardize the entries.

**Comment by MihaiSurdeanu** [comment]
Ok with me then!

@bnmin: does this change impact BBN in any negative way?

**Comment by kwalcock** [comment]
If an underscore is a requirement, it should (eventually) be added to the unit tests.

**Comment by bnmin** [comment]
Sounds good to me. It should be just some minor changes on our side. @MihaiSurdeanu 

Thanks! @dianakolusheva

**Comment by kwalcock** [comment]
I did check for spaces in the node or branch names and found none.  If it turns out to be a hard requirement, I can submit the code.

**Pull request merged**
