### PR TITLE
Add wm_compositional_metadata

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@zupon, this will likely fail on travis, sometime after the output of
```
Adding non-leaf node for temporal
Adding leaf node for crop_season
Adding leaf node for season
```
That would be the place to look for a problem.

**Comment by kwalcock** [comment]
The not-very-helpful exception that is produced is
```
[info] - should load without exception *** FAILED ***
[info]   org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
[info]  in 'reader', line 538, column 17:
[info]                   - OntologyNode:
[info]                     ^
[info] expected <block end>, but found BlockEntry
[info]  in 'reader', line 543, column 17:
[info]                     - OntologyNode:
[info]                     ^
```

**Comment by kwalcock** [comment]
After this passes, a merge and then update via sbt should get you the file via the copy in ivy2.

**Comment by kwalcock** [comment]
It looks like lines 538 and 543 are better indicators.  Something might be indented too far.  A leaf node can't have other leaf nodes.

**Comment by zupon** [comment]
I checked both of those lines and it doesn't look like anything is incorrectly indented. Also looking around temporal/crop_season and temporal/season I don't see anything wrong with the indentation or missing a `name` or anything.

**Comment by zupon** [comment]
Ah nevermind. On the copy of wm_compositional_metadata.yml` that you have in yours there is an indentation error. When playing around with the ontology I fixed that error and one other like it.

**Comment by kwalcock** [comment]
Let me know if you don't have permissions to look at the Travis output.  I could at least copy and paste for you.

**Comment by kwalcock** [comment]
@zupon, this message `Spaces: ArrayBuffer(wm, concept, causal_factor, health_and_life, disease, alcohol drug and substance abuse)` means the leaf node with the last bit of text has spaces in it and shouldn't.

**Comment by kwalcock** [comment]
I.e., `alcohol drug and substance abuse` should have _s.

**Comment by zupon** [comment]
@kwalcock Ok to merge now that all tests are passing?

**Comment by kwalcock** [comment]
Congratulations!  Go for it.

**Pull request merged**
