### PR TITLE
Merge metadata changes from spilioeve

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I'm not sure what editor or library the file went through, but if it goes again, perhaps there can be a run in which only the format is changed and another pass for content changes.  I'm not sure whether everyone's library is able to handle nodes that span lines and those were reverted, but just as a side effect of minimizing the diff.

**Comment by BeckySharp** [comment]
ok -- so @kwalcock @chanys @bgyori @spilioeve is this now ready?

**Comment by kwalcock** [comment]
I think so, but someone else may know better.  They are welcome to the big green button.

**Comment by bgyori** [comment]
I think this looks good, thanks @kwalcock for sorting out the spurious diffs.

**Pull request merged**
